name: "KiBot"

on:
  push:
    paths:
      - '**/*.kicad*'
      - '**/*.kibot.yaml'
      - '**/kibot-ci.yml'
    tags:
      - '*'

    # Will this cause tags to not work also??
    branches-ignore:
      - 'master'
      - 'main'
      

env:
  GERBERS_JLCPCB: jlcpcb-gerber-${{github.event.repository.name}}-${{github.sha}}-${{github.ref_name}}
      
jobs:
  KiBotImageCache:
    runs-on: ubuntu-latest
    steps:
      - name: Restore MySQL Image Cache if it exists
        id: cache-docker-kicad6
        uses: actions/cache@v3
        with:
          path: ci/cache/docker/cache-docker-kicad6
          key: cache-docker-kicad6

      - name: Update cache-docker-kicad6 Image Cache if cache miss
        if: steps.cache-docker-kicad6.outputs.cache-hit != 'true'
        run: docker pull ghcr.io/inti-cmnb/kicad6_auto_full:1.6.3 && mkdir -p ci/cache/docker/kicad6_auto_full && docker image save ghcr.io/inti-cmnb/kicad6_auto_full:1.6.3 --output ./ci/cache/docker/kicad6_auto_full/kicad6.tar

      - name: Use cache-docker-kicad6 Image Cache if cache hit
        if: steps.cache-docker-kicad6.outputs.cache-hit == 'true'
        run: docker image load --input ./ci/cache/docker/kicad6_auto_full/kicad6.tar

      # - name: Start containers
      #   run: docker compose up -d

  
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:1.6.3
    steps:
      
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
#        token: '${{ secrets.PAT_TOKEN }}'

    - name: KiBot
      run: |
        kibot -d build -c kibot/config.kibot.yaml

    # - name: KiBot
    #   run: |
    #     kibot -d build -c kibot/config.kibot.yaml && \
    #     mv ./build/gerber-files/jlcpcb-gerber.zip ./build/gerber-files/${{ env.GERBERS_JLCPCB }}.zip
   
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        #name: artifacts-${{github.sha}}
        path: ./build
        if-no-files-found: error
        
    - name: Build Tagged Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          ./build/gerber-files/${{ env.GERBERS_JLCPCB }}.zip
          ./build/thumbnails/front.png
          ./build/thumbnails/back.png
        body: |
          ![Front](${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/front.png)
          ![Back](${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/back.png)

